### ISSUE TITLE
Request: Lite Version of Object Observer

### ISSUE THREAD

**Issue by AjayTheWizard** [gullerya/object-observer#127]
I am happy to found this Awesome Library. But Only Problem is bundle size for non CDN Users.
Compressed Size is ~8kB. Is there any chance of making Lite Version of this Library?
Thanks in Advance.

**Comment by gullerya** [comment]
Hi, thanks!
You can take a look onto the sources, it's just one file. I can't see a way to make it lighter.

Yet - just looking how the downloads looks like (it's gzipped, or something like that):
- non-minified size of download is 4.7kB (~18kB)
- minified size of download is 3.4kB (~9kB)

So any zipping like gzip lowering it down even more.

**Comment by gullerya** [comment]
Closing this - no action item visible/possible as of now.
