### ISSUE TITLE
handle correctly circular shaped object passed for observation

### ISSUE THREAD

**Issue by gullerya** [gullerya/object-observer#129]
As came to known from #128 currently there is mis-handling of an objects when having circular shape during the proxification phase.
I've considered 2 ways to handle this situation:
- throw an error so not make any assumptions on behalf of consumer and also not creating some possible ambiguity
- handle it while gracefully, proxifying the first instance encountered and __nullifying__ the nested circulars.

Since right now there is no support to declaratively skip paths from proxification (considered as a future item), I'll take the second, graceful approach given no convenient tool available for consumer to handle such a situation.
It might happen, that one the 'skip paths' functionality available, I'll probably change this behavior to be an option one above.

**Comment by BennyH26** [comment]
I think the second approach (nullifying nested circulars) is probably the best approach and is most likely what users will expect.

**Comment by gullerya** [comment]
Fixed in `5.1.7`, @BennyH26 FYI.

**Comment by BennyH26** [comment]
Thank you!On Mar 1, 2023, at 2:30 AM, Yuri Guller ***@***.***> wrote:﻿
Closed #129 as completed.
