### ISSUE TITLE
Using Symbols for isObservable

### ISSUE THREAD

**Issue by akuma06** [gullerya/object-observer#13]
Hi!

I've been through the code in order to use this as a dependency for one of my vanilla JS project and I've seen that the method `Observable.isObservable` uses some typeof checks to verify that the object is observable.

I think that it might be better to use Symbols like the `Array.isArray` method. To be more precise, there is an article that goes deep on the advantages to use Symbols and how they are used in javascript `is` methods [here](https://jakearchibald.com/2017/arrays-symbols-realms/).

**Comment by gullerya** [comment]
Done and released in version 1.1.5.
Thanks!
