### ISSUE TITLE
Observe specific path

### ISSUE THREAD

**Issue by fronteed** [gullerya/object-observer#21]
Some additions to API are needed to observe a specific object path.

In example, I've an object like:
```js
{
 a: {
  b: {
   c: 'value'
  }
 }
}
```

I would like to subscribe only to "a.b.c." updates (even if it doesn't exist yet), not to any update in object.

**Comment by gullerya** [comment]
I'll consider it, NP.
One question so far: would you expect that only the specified path will be listened to, or anything from that path and deeper?
Or both options available and chosen by consumer explicitly while registering observers?

**Comment by fronteed** [comment]
>both options available and chosen by consumer explicitly while registering observers

>only the specified path will be listened to by default

**Comment by gullerya** [comment]
released as a part 2.1 vesion, thanks tonis2 for the lead!!!
