### ISSUE TITLE
issue: The js fiddle demo is not working

### ISSUE THREAD

**Issue by Jarajesh** [gullerya/object-observer#23]
hi , thanks for the library.
the demo link provided in [jsfiddle](https://jsfiddle.net/gullerya/5a4tyoqs/)
is not working.
ReferenceError: Observable is not defined

**Comment by gullerya** [comment]
Fixed (should have redefine the library loading since i've moved it to be ES6 module only).

**Comment by Jarajesh** [comment]
The updated fiddle answers a lot of my questions. Thanks for a quick turnaround.
