### ISSUE TITLE
Consider adding array of paths to observer options

### ISSUE THREAD

**Issue by emahuni** [gullerya/object-observer#54]
This lib is great!

Could you add the ability to do the following:

```js
let user = {
        firstName: 'Aya',
        lastName: 'Guller',
       phone: {
           number: '023887942'
        },
        address: {
            city: 'of mountaineers',
            street: 'of the top ridges',
            block: 123,
            extra: {
                data: {}
            }
        }
    },
    oUser = Observable.from(user);
 
oUser.observe(callback, {paths: [ 'firstName', 'address' ]});
oUser.observe(callback, {pathsOf: [ 'phone', 'address.extra' ]});
oUser.observe(callback, {pathsFrom: [ 'phone', 'address' ]});
```

They'd function the same way as their counterparts but only that we are observing multiple paths.

**Comment by gullerya** [comment]
Hi!

Thanks for the feedback!

As of the question: I've almost came to suggest to just set an observation separately for each case, but it's not convenient indeed and actually not possible with the same callback - lib will prevent setting the same callback twice :)

So I'll check an API and the implementation, your request sounds reasonable, I'd just like to see how it can be formalised to something simple and intuitive.

Will update ASAP.

**Comment by gullerya** [comment]
To add to this ticket - memo to myself :) - this is a good change to rethink the terms of this API, since even to me a distinction between those options becomes less prominent over time.

**Comment by gullerya** [comment]
Closing as dated, please reopen if needed.
