### ISSUE TITLE
Fiddle not working?

### ISSUE THREAD

**Issue by jgg3** [gullerya/object-observer#58]
I would like to try this library, but I can't get past loading.  Even the fiddle linked doesn't work at all ("import a reserved word").  I have tried many permutations of require, import, etc, but am getting errors about modules.
Is there a working fiddle for this?

**Comment by gullerya** [comment]
Checking

**Comment by gullerya** [comment]
Indeed the links in both the JSFiddle and the CodePen needed to be adjusted, sorry for that.
All is fixed and working now.

Please notify me if any issues emerge.

> Please discard the error note in the JSFIddle, it's just a code assist of their own, that complaints on the ES6 syntax

**Comment by jgg3** [comment]
It appears to be choking on the import:  This is from the Chrome console:

_dist-editor.js?e4c1576692d4b018ccbce22ce347086ca86640bc:1 Unrecognized feature: 'display-capture'.
switchGrid @ _dist-editor.js?e4c1576692d4b018ccbce22ce347086ca86640bc:1
(index):1 A cookie associated with a cross-site resource at http://fiddle.jshell.net/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
2**rawgit.com/gullerya/object-observer-js/master/dist/object-observer.js:1 Failed to load resource: the server responded with a status of 404 ()**
?editor_console=:142 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://rawgit.com/gullerya/object-observer-js/master/dist/object-observer.js
DevTools failed to load SourceMap: Could not load content for https://jsfiddle.net/js/createStream.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by gullerya** [comment]
I see what's going on.
That 404 is due to the wrong URL in the import (`object-observer-js` was renamed years ago :) ).
And the **latest** JSFiddle gets it right, but the link I've put in the readme.md has not specifies `/latest`, therefore JSFIddle goes actually to the first verions - which is wrong.

I"m fixing the link in the code and will be pushing this change in a minutes.
CodePen, does it right, getting by default the latest version, so may be useful as of now.

**Comment by gullerya** [comment]
fixed in 3.1.1, please see if you get it okay

**Comment by gullerya** [comment]
Closing, please reopen if any further issue.
