### ISSUE TITLE
CodePens no longer work (CDN maybe)?

### ISSUE THREAD

**Issue by ChristopherMoll** [gullerya/object-observer#85]
I just tried playing with the CodePens and the library wouldn't load (403).  I'm about 5min into even knowing this library exists, so forgive me for not being more helpful, but I figured I'd report it.

**Comment by gullerya** [comment]
Absolutely right.
I see that deploy process got broken - fixing it now, meanwhile I've updated the CodePens to work with the latest version.

Thanks and will update this issue as resolve.

**Comment by gullerya** [comment]
Fixed, having the CodePens running with the lib pulled by version.

Thank you very much!
