### ISSUE TITLE
Working with Jest

### ISSUE THREAD

**Issue by martinchrzan** [gullerya/object-observer#87]
Hi, I am not able to make it work with Jest, getting 

 SyntaxError: Unexpected token 'export'

    > 2 | import * as Observable from "object-observer/dist/object-observer.min.js";
        | ^

I tried adding transformIgnorePatterns into jest.config.ts
"node_modules/(?!object-observer/)"

with no luck.

Anyone using object-observer with jest?

**Comment by martinchrzan** [comment]
Rookie mistake, you can have only one pattern in transformIgnorePatterns, I already had fluentUI so I added another one 
```
"node_modules/(?!(@fluentui)/)",
"node_modules/(?!object-observer/)"
```

but it should be like this:
`"node_modules/(?!(@fluentui)|(object-observer)/)",`

**Comment by gullerya** [comment]
Hi,
I can't know if anyone works with Jest using `object-observer`, well, people do not report that thing.

But from other projects experience and the error + some search on the topic - your Jest/env is not supporting the ES6 modules yet.

I'd propose those as an options:
- using ES6 modules compatible NodeJS (14)
- ensure that Babel is tuned to work with ES6 modules (or relevant TypeScript setup applied, if TS is your env)
- indeed added that piece of config as you've mentioned to the `jest.config.ts` to get the `object-observer` transpiled into pre-ES6-modules fashion

```
{
  "jest": {
    "transformIgnorePatterns": [
      "node_modules/(?!@ngrx|(?!deck.gl)|ng-dynamic)"
    ]
  }
}
```

**Comment by gullerya** [comment]
Oh, okay, so you got this!
Great then!
