### ISSUE TITLE
Proxy only plain objects

### ISSUE THREAD

**Issue by soanvig** [gullerya/object-observer#88]
Hello. I have object, that I want to observe, let's call it "state". State however contains instances of classes, which lost their prototype methods after observing.

I would suggest to observe only plain objects.

```
class Entity { myMethod () {} }
const state = { entity: new Entity() };
const obState = Observable.from(state);

obState.entity.myMethod // undefined
```

**Comment by soanvig** [comment]
I needed that quick, so I hotfixed it like so:

https://github.com/soanvig/object-observer/commit/1edca987ca4c479431997629f2d9612cb8a38a35

**Comment by gullerya** [comment]
Hi.

I would not like to go down this way, definitely not straight forward as your proposal, since it breaks backward compatibility for those who also uses classes, but is ready to give up on the methods when observation used.

Yet, I'd like to keep this issue open for some while to let other opinions in, it's not the first time cloning is bespoken.

> PS: I must say that in general `object-observer` adheres to SOA design, which differs from the pure OOP in that data, state in your case, is strictly separated from the logic operating on it. It's even explicitly stated in [this doc](https://github.com/gullerya/object-observer/blob/main/docs/observable.md#observablefrominput-options) that `object-observer` works with __own enumerables__, thus NOT expecting to handle prototypical aspects of pure data graphs.

**Comment by soanvig** [comment]
Sure, that's perfectly valid argument :-) Definitely it's not simple, it's just my case only - probably.

**Comment by gullerya** [comment]
Closing this, anyone interested in reviving discussion around this functionality, please reopen and add your thoughts.
