### ISSUE TITLE
Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by xeroxstar** [gullerya/object-observer#89]
I am trying to run this module but i am getting an error, `Right-hand side of 'instanceof' is not an object` and i had to remove this line to make it work again:

```
 if (target instanceof Date  || target instanceof Error) {
            throw new Error(`${target} found to be one of a on-observable types`);
}
```

**Comment by gullerya** [comment]
Checking.

**Comment by gullerya** [comment]
@xeroxstar can you please provide some info on your environment?
This kind of error can happen, IMHO, only when `Date` or `Error` object, which are pretty much standard ones on all modern browsers and Node, are not defined.

**Comment by xeroxstar** [comment]
Hello,
I am still looking for the problem, surprisingly, it was working before on Node and on the Browser, I think the `babel `has something to do with that, I will let you know when I will figure out. For now I just removed the few lines from the code, and it's working.

**Comment by gullerya** [comment]
Babel is a good place to look at - probably your transpilation target goes too far back or something like this.

Anyway, those lines are important :), so I'd suggest to have it working with them.

Let me know if you find anything or, please, close the issue if will become not relevant.

**Comment by gullerya** [comment]
Closing this one, please reopen if any new info becomes available.
